name: Build MAUI Android 🛠️

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  publish:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          
      - name: Install MAUI workload
        run: dotnet workload install maui
      - name: Build
        run: dotnet build ProjControleFinanceiroSlnMobile/ProjControleFinanceiroSlnMobile.sln -c Release -f:net7.0-android
